### ISSUE TITLE
Failed to initialize vosk library

### ISSUE THREAD

**Issue by jaythub** [igor725/lua-vosk#1]
cd test
lua main.lua
lua: main.lua:9: Failed to initialize vosk library: libvosk.so was not found

I have a symbolic link to libvosk.so in the test directory

libvosk.so was tested with C code and it works

raspberrypi armv7

**Comment by igor725** [comment]
Hello! I think your libvosk is not in LD_LIBRARY_PATH. Try to specify path to the libvosk.so explicitly in vosk.init function call (e.g. `vosk.init('./libvosk.so')`)

**Comment by jaythub** [comment]
Solved!

vosk.init('./libvosk.so')

Thank you
