### ISSUE TITLE
Exits at vosk.wavguess(f) without an error

### ISSUE THREAD

**Issue by jaythub** [igor725/lua-vosk#2]
I added a print("hello luavosk") after vosk.wavguess(f) 
Nothing shows up

test directory
https://github.com/igor725/lua-vosk/releases/download/v1.3-4/lua51-mingw-x64.zip

libvosk.dll: 
https://github.com/alphacep/vosk-api/releases/download/v0.3.45/vosk-win64-0.3.45.zip

libvosk.dll was tested with C code and it works
https://github.com/alphacep/vosk-api

windows x64

**Comment by igor725** [comment]
Probably your Lua VM is compiled with different compiler. You need to build `lua-vosk` yourself with MSVC (I think). MSVC's and MinGW's runtime uses different IO handles to store files in memory. So libraries compiled by different compilers may not work correctly in one application.

**Comment by igor725** [comment]
> libvosk.dll was tested with C code and it works

The function `wavguess` has nothing to do with `libvosk.dll`, by the way. It's implemented in my library only.

**Comment by jaythub** [comment]
The exit at vosk.wavguess(f) only happens with Love 11.2
https://github.com/love2d/love/releases/download/11.2/love-11.2-win64.zip

I built Lua 5.4.6 and tested after this issue and thought the problem was consistent.
https://www.lua.org/ftp/lua-5.4.6.tar.gz
https://www.lua.org/manual/5.4/readme.html
raylib 5.0 Windows Installer 64bit (MinGW compiler) ... raylib\w64devkit\bin
make mingw

After two days of testing, the error i get with lua 5.4.6 is
lua: error loading module 'luavosk' from file '.\luavosk.dll':
        The specified module could not be found.

I was trying to avoid compiling headaches and bloat.

I am sure if i follow your instructions, it will work since you have tested it.
https://docs.igvx.ru/lua-vosk/
Thanks

**Comment by igor725** [comment]
> After two days of testing, the error i get with lua 5.4.6 is

Pre-built `lua-vosk` release binary is complied ONLY for Lua 5.1 (it won't work with Lua > 5.1)

If you avoid using `wavguess` with release binary in LÖVE, it will work just fine (probably). Sadly, I don't have enough time to fix it atm.

**Comment by jaythub** [comment]
> If you avoid using wavguess with release binary in LÖVE, it will work just fine (probably). Sadly, I don't have enough time to fix it atm.

Replacing wavguess ... with

file = love.filesystem.newFile( 'rec.wav' )
decoder = love.sound.newDecoder( file)
local nsamp, isfloat =decoder:getSampleRate( ), false

worked! 

I will do some tests, compile Lua 5.1, test some more and let you know what i get.
Thanks

**Comment by igor725** [comment]
I think I fixed `wavguess` function. Precompiled binary should not crash your VM anymore.
https://github.com/igor725/lua-vosk/releases/tag/v1.3-5

**Comment by jaythub** [comment]
Fixed!

Love 11.2 and Lua 5.1.5 work.

Thanks
